6.0


1
0001
Goal for overs
SIGNAL_ONLY
2
False
False
1
False
False
3000
90
5
2
2

CUSTOM_BELOW

10
10
FIXED
False
False
False
False
False



False


INCREMENT
goal
1
NONE

1
True
2
TIME_UNSUSPENDED
Time since unsuspended > 60 seconds
2
GREATER
60
HISTORIC_RELATIVE_ODDS
Last Traded price < Last Traded price 65 seconds ago - 15 ticks
18
True
2
1

LTP
True
0
LESS
True
2
1

LTP
False
65
MINUS
15
TICKS

